import 'package:flutter/material.dart';

List<Color> colorsList = [
  Colors.purpleAccent,
  Colors.deepOrange,
  Colors.limeAccent,
  Colors.greenAccent,
  Colors.black,
  Colors.white,
  Colors.amberAccent,
  Colors.indigo,
  Colors.brown,
  Colors.pink,
  Colors.amber,
  Colors.tealAccent,
  Colors.teal,
  Colors.red,
  Colors.yellowAccent,
  Colors.blue,
  Colors.orangeAccent,
  Colors.cyan,
  Colors.lightBlueAccent,
  Colors.deepPurpleAccent,
  Colors.lightGreenAccent,
  Colors.blueGrey,
  Colors.cyanAccent,
  Colors.yellow,
  Colors.orange,
  Colors.lightGreen,
  Colors.purple,
  Colors.lime,
  Colors.deepPurple,
  Colors.blueAccent,
  Colors.grey,
];
